#!/usr/bin/env bash
#
# integration tests, compare output of executable with saved answer.

# Dirs
declare -r TESTS=$(cd "$(dirname "${BASH_SOURCE:-$0}")" || exit; pwd)
declare -r ROOT=$(dirname "$TESTS")
declare -r DATA=$ROOT/data

run() {
  local -r example=$1
  local -r data=$2
  local -r cwd=$(pwd)

  cd "$ROOT" || exit 1
  cargo run --release --example "$example" < "$data"
  cd "$cwd" || exit 1
}

for data in $DATA/*/*.txt; do
  input=$(basename "$data" .txt)
  expected_output="$input.out"
  example=$(basename "$(dirname "$data")")
  diff --brief "$DATA/$example/$expected_output" <(run "$example" "$data")
  test $? && echo "OK $example $input"
done
